backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "preprints"
    label: "Preprints"
    folder: "content/preprints"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Bahadır Arıcı" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Show Reading Time", name: "ShowReadingTime", widget: "boolean", default: true }
      - { label: "Show Word Count", name: "ShowWordCount", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "records"
    label: "Records"
    folder: "content/records"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Bahadır Arıcı" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Show Reading Time", name: "ShowReadingTime", widget: "boolean", default: true }
      - { label: "Show Word Count", name: "ShowWordCount", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Hide Meta", name: "hidemeta", widget: "boolean", default: true }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/research.md"
        label: "Research"
        name: "research"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Hide Meta", name: "hidemeta", widget: "boolean", default: true }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/the-puppet-condition.md"
        label: "Monograph"
        name: "puppet"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Hide Meta", name: "hidemeta", widget: "boolean", default: true }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/whitepaper.md"
        label: "Whitepaper"
        name: "whitepaper"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Hide Meta", name: "hidemeta", widget: "boolean", default: true }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/privacy.md"
        label: "Privacy"
        name: "privacy"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Hide Meta", name: "hidemeta", widget: "boolean", default: true }
          - { label: "Body", name: "body", widget: "markdown" }
